### ISSUE TITLE
Incorrect Property Type Generated

### ISSUE THREAD

**Issue by ray-vgw** [yortus/http-schemas#30]
Hi

Using the latest version of http-schemas (0.13.1) and typescript 4.6.2, I'm getting an incorrect type generated.  In the following example:

```
const Result = t.object({
    date: t.string,
    foobar: t.optional(t.number),
});
```

`foobar` is being generated as an `unknown`, see below:

```
declare const Result: import("http-schemas").TypeInfo<{
    date: string;
    foobar?: unknown;
}>;
```

With http-schemas 0.10.1, this generates (very differently) `foobar` which resolves to `number | undefined`

```
declare const Result: t.object<{
    date: t.string;
    foobar: t.optional<t.number>;
}>;
```

**Comment by yortus** [comment]
Thanks @ray-vgw. There was a type inference regression in the `rtti` library which is now fixed. This should now be working as expected in v0.13.2.
